### ISSUE TITLE
[META][FEAT] ember-cli platforms integration

### ISSUE THREAD

**Issue by runspired** [poetic/ember-cli-cordova#192]
This is a tracking issue for ember-cli platforms integration.  You can read the RFC for platforms here: https://github.com/ember-cli/rfcs/pull/35

This is a feature which I'll be working on landing in ember-cli in the very near future, as soon as the RFC finishes a review process.

This integration would be a breaking change, as it would replace the public command API.

I've opened this issue for discussion on topics such as

- [ ] what configuration settings we'd like to preserve/add
- [ ] what belongs in a default cordova platform addon
- [ ] what files we'd like to make easier to work with (such as config.xml)

As well as to start fleshing out a happy path from the state of the repo at the moment to it's future as a platform plugin.  The intention is to run ember-cli-cordova through several cleanup / preparation iterations before the conversion to get the addon in good shape before making the breaking change to commands.
